// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJRC5km1T5m7DNJlHj3mAtn7QiQctVg8',
    appId: '1:208621128467:web:d2eba432603b8787b928e6',
    messagingSenderId: '208621128467',
    projectId: 'iot-crayfish-monitoring-system',
    authDomain: 'iot-crayfish-monitoring-system.firebaseapp.com',
    databaseURL: 'https://iot-crayfish-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-crayfish-monitoring-system.firebasestorage.app',
    measurementId: 'G-4Q8706C2Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkHuMFrqTLTPCyQFVaCzMn93rIXC9rZLg',
    appId: '1:208621128467:android:de4f4fcaf6ab1f06b928e6',
    messagingSenderId: '208621128467',
    projectId: 'iot-crayfish-monitoring-system',
    databaseURL: 'https://iot-crayfish-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-crayfish-monitoring-system.firebasestorage.app',
  );
}
